disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "jasonblujaxianjackson.com"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "blujaxian"
  email = "blujaxian@jasonblujaxianjackson.com"
  image = "img/2024-11-11 20.56.54.jpg"
  imageQuality = 96
  headline = "Just a geeky dude!"
  bio = "A little bit about you"
  links = [
    { email = "mailto:blujaxian@jasonblujaxianjackson.com" },
    #{ link = "https://link-to-some-website.com/" },
    #{ amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #{ apple = "https://www.apple.com" },
    #{ blogger = "https://username.blogspot.com/" },
    #{ bluesky = "https://bsky.app/profile/username" },
    { codepen = "https://codepen.io/blujaxian" },
    { dev = "https://dev.to/blujaxian" },
    { discord = "https://discord.gg/5YjwARqt" },
    #{ dribbble = "https://dribbble.com/username" },
    #{ facebook = "https://facebook.com/username" },
    #{ flickr = "https://www.flickr.com/photos/username/" },
    #{ foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/blujaxian" },
    { gitlab = "https://gitlab.com/blujaxian" },
    #{ google = "https://www.google.com/" },
    #{ hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/blujaxian" },
    #{ itch-io = "https://username.itch.io" },
    #{ keybase = "https://keybase.io/username" },
    #{ kickstarter = "https://www.kickstarter.com/profile/username" },
    #{ lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://www.linkedin.com/in/jason-jackson-8a38b2349/" },
    { mastodon = "https://linuxrocks.online/@blujaxian" },
    { medium = "https://medium.com/blujaxian-TheLinuxUser" },
    #{ microsoft = "https://www.microsoft.com/" },
    #{ orcid = "https://orcid.org/userid" },
    { patreon = "https://www.patreon.com/blujaxian" },
    #{ pinterest = "https://pinterest.com/username" },
    #{ reddit = "https://reddit.com/user/username" },
    #{ researchgate = "https://www.researchgate.net/profile/username" },
    #{ slack = "https://workspace.url/team/userid" },
    #{ snapchat = "https://snapchat.com/add/username" },
    { soundcloud = "https://soundcloud.com/blujaxian" },
    { spotify = "https://open.spotify.com/user/blujax" },
    #{ stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/profiles/blujaxjrj" },
    #{ telegram = "https://t.me/username" },
    { threads = "https://www.threads.net/@blujaxian" },
    { tiktok = "https://tiktok.com/@blujaxian" },
    #{ tumblr = "https://username.tumblr.com" },
    { twitch = "https://twitch.tv/blujaxian" },
    #{ twitter = "https://twitter.com/username" },
    { x-twitter = "https://twitter.com/blujaxian" },
    #{ whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/username"},
    { ko-fi = "https://ko-fi.com/blujaxian" },
    #{ codeberg = "https://codeberg.org/username"},
  ]
